package com.example.order.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents an order in the Order Management System.
 *
 * <p>This JPA entity persists order data with comprehensive audit fields.
 * Automatically calculates total amount and enforces data consistency via constraints.</p>
 */
@Entity
@Table(name = "orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    /**
     * Unique order identifier, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the customer who placed the order.
     * Must not be null and must be at most 120 characters.
     */
    @Column(nullable = false, length = 120)
    private String customerName;

    /**
     * Name or description of the ordered item/product.
     * Must not be null and must be at most 150 characters.
     */
    @Column(nullable = false, length = 150, name = "item_name")
    private String itemName;

    /**
     * Number of units ordered.
     * Must be a positive integer.
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Unit price for each ordered item.
     * Stored with precision 12,2 (supports up to $9,999,999.99).
     */
    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal unitPrice;

    /**
     * Timestamp when this order was created.
     * Set automatically on insert and never updated.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the last update to this order.
     */
    @Column
    private LocalDateTime updatedAt;

    /**
     * Current status of the order lifecycle.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    /**
     * Supported order statuses across the order lifecycle.
     */
    public enum Status {
        /**
         * Order created but not yet being processed.
         */
        NEW,
        /**
         * Order is actively being fulfilled.
         */
        PROCESSING,
        /**
         * Order has been successfully completed.
         */
        COMPLETED,
        /**
         * Order was cancelled before completion.
         */
        CANCELLED
    }

    /**
     * Calculates the total order amount (quantity × unitPrice).
     *
     * @return total amount, or ZERO if quantity or unitPrice is null
     */
    public BigDecimal getTotalAmount() {
        if (quantity == null || unitPrice == null) {
            return BigDecimal.ZERO;
        }
        return unitPrice.multiply(BigDecimal.valueOf(quantity));
    }

    /**
     * Pre-persist hook: sets audit timestamps on insert.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Pre-update hook: updates the modification timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}